nameOverride: ""
fullnameOverride: ""

replicaCount: 3

image:
  repository: rminol/devops-test
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}


podSecurityContext: {}
  # fsGroup: 2000

# securityContext:
#   capabilities:
#     drop:
#     - ALL
#   # readOnlyRootFilesystem: true
#   runAsNonRoot: true
#   runAsUser: 1000

service:
  type: ClusterIP
  port: 8080


mySQLDatabase:
  host: my-db
  port: 3306
  user: my-user
  password: my-password
  db: targets
